version: "3.8"

services:
  app:
    build: .
    container_name: store_intelligence_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python store-intelligence/app/main.py
